// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK0GqsRyaVpM5R9WeOpWhmfttYYa1kfZU',
    appId: '1:487435523259:web:c57242e1dca19b27fcc59e',
    messagingSenderId: '487435523259',
    projectId: 'asset-manager-78d3a',
    authDomain: 'asset-manager-78d3a.firebaseapp.com',
    storageBucket: 'asset-manager-78d3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzoVZe8g0aaZ2aW7jaf9AT1CmT4qa3Yw',
    appId: '1:487435523259:android:14ed1125302e5aeffcc59e',
    messagingSenderId: '487435523259',
    projectId: 'asset-manager-78d3a',
    storageBucket: 'asset-manager-78d3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBN_-n81MZHYxpH3qo_D3PbGRuYmEKOcM',
    appId: '1:487435523259:ios:465bdaa9ba12f536fcc59e',
    messagingSenderId: '487435523259',
    projectId: 'asset-manager-78d3a',
    storageBucket: 'asset-manager-78d3a.firebasestorage.app',
    iosBundleId: 'com.example.b3q1FlutterProjectAssetManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBN_-n81MZHYxpH3qo_D3PbGRuYmEKOcM',
    appId: '1:487435523259:ios:465bdaa9ba12f536fcc59e',
    messagingSenderId: '487435523259',
    projectId: 'asset-manager-78d3a',
    storageBucket: 'asset-manager-78d3a.firebasestorage.app',
    iosBundleId: 'com.example.b3q1FlutterProjectAssetManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK0GqsRyaVpM5R9WeOpWhmfttYYa1kfZU',
    appId: '1:487435523259:web:430d9fcf1db054e5fcc59e',
    messagingSenderId: '487435523259',
    projectId: 'asset-manager-78d3a',
    authDomain: 'asset-manager-78d3a.firebaseapp.com',
    storageBucket: 'asset-manager-78d3a.firebasestorage.app',
  );

}